version: '2'
services:
  web:
    image: deepqa:latest
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - /home/csp/repo/chatbot/DeepQA/logs:/root/DeepQA/logs
      - /home/csp/repo/chatbot/DeepQA/save/model-meneame:/root/DeepQA/save/model
      - /home/csp/repo/chatbot/DeepQA/save/model-meneame:/root/DeepQA/save/model-server
      - /home/csp/repo/chatbot/DeepQA/data/samples:/root/DeepQA/data/samples
    depends_on:
      - redis
  redis:
    image: redis
